[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
casi_escrow = "6utjMbb5ovFHUdMcMWaGc5ovmVhLryVRLEzYPWzeBosg"

[programs.mainnet]
casi_escrow = "6utjMbb5ovFHUdMcMWaGc5ovmVhLryVRLEzYPWzeBosg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
casi_escrow = "6utjMbb5ovFHUdMcMWaGc5ovmVhLryVRLEzYPWzeBosg"

[scripts]
test = "npx ts-mocha -p tests/tsconfig.json -t 1000000 tests/**/*.ts"
